TESTDATA = {
    "email_p": "progmasterstn@endtest-mail.io",
    "username_p": "ProgMastersTN",
    "password_p": "Test12345!",
    "succesful_msg": "The verification email has been sent to your email address, please verify your registration before log in",
    "negative_email": "nemkell.email.hu",
    "negative_username": "1",
    "negative_password": "asd",
    "negative_password_again": "dsa",
    "TAB_email": "You must enter your email address",
    "TAB_username": "You must enter the name",
    "TAB_password": "You must enter a password",
    "TAB_password_again": "You must enter the password again",
    "negative_email_msg": "Not a valid email",
    "negative_username_msg": "The length should be minimum 4 characters",
    "negative_password_msg": "The length should be minimum 8 characters",
    "negative_password_again_msg": "The passwords do not match",
    "Login_username_p": "ProgMastersTN",
    "Login_password_p": "Test12345!",
    "negative_login_username": "qwert",
    "negative_login_password": "sdfg",
    "negative_login_msg": "Wrong username or password",
    "contact_name": "Brendon Schlosserr",
    "contact_email": "probaprorba@proba.com",
    "contact_field": "Ez egy próba üzenet. ;)",
    "contact_msg_succ": "Your message has been sent.",
    "address": "Budapest, Irányi utca 3., 1056.",
    "ProgMusix_URL": "http://localhost:4200/"
}