# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    jobs:
  test:
    runs-on: ubuntu-latest

    services:
      webapp:
        image: <your-docker-image> # Cseréld le a te Docker image nevedre
        ports:
          - 4200:4200 # Állítsd be a megfelelő portot
        options: > 
          --health-cmd="curl --fail http://localhost:8080 || exit 1" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

      selenium:
        image: selenium/standalone-chrome:latest # Vagy standalone-firefox:latest
        ports:
          - 4200:4200

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Vagy a szükséges verzió

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests
      env:
        SELENIUM_REMOTE_URL: http://localhost:4200/wd/hub
        WEBAPP_URL: http://localhost:4200
      run: |
        pytest --maxfail=1 --disable-warnings -v
