
name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      backend:
        image: lenartl/webshop-backend:sprint-1
        ports:
          - 8080:8080
          
      frontend:
        image: lenartl/webshop-frontend:sprint-1
        ports:
          - 4200:4200
          
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        
        env:
          MYSQL_DATABASE: webshop
          MYSQL_HOST: localhost
          MYSQL_NAME: root
          MYSQL_ROOT_PASSWORD: test1234
        
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install mysql-connector-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Create MySQL config file
      run: |
        echo "[client]" > ~/.my.cnf
        echo "user=root" >> ~/.my.cnf
        echo "password=test1234" >> ~/.my.cnf
        echo "host=127.0.0.1" >> ~/.my.cnf

    - name: Show MySQL tables
      run: |
        mysql webshop -e "SHOW TABLES;"

    - name: Verify MySQL connection
      run: |
        mysql -h"127.0.0.1" -uroot -ptest1234 -e "SHOW DATABASES;"

    - name: Check MySQL container status
      run: |
        mysqladmin -h"127.0.0.1" -uroot -ptest1234 ping

    - name: Query message table
      run: |
        mysql -h"127.0.0.1" -uroot -ptest1234 webshop -e "SELECT * FROM message LIMIT 1;"

    - name: Check for message table in webshop database
      run: |
        mysql -h"127.0.0.1" -uroot -ptest1234 webshop -e "SHOW TABLES LIKE 'message';"

    - name: Check MySQL logs
      run: |
        docker logs <mysql-container-id>
        
    - name: Debug message table
      run: |
        mysql -h"127.0.0.1" -uroot -ptest1234 webshop -e "SHOW TABLES LIKE 'message';"
      

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      env:
        FRONTEND_URL: http://localhost:4200
        BACKEND_URL: http://localhost:8080
        HOST: localhost
        PORT: 3306
        USERNAME: root
        PASSWORD: test1234
        DATABASE: kiskutya
        
        
        
      run: |
        pytest --alluredir=allure-results

    - name: Allure Report action from marketplace
      if: always()
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
