name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Start all containers
      run: |
        docker run -d --name frontend -p 4200:4200 lenartl/webshop-frontend:sprint-1
        docker run -d --name database -e MYSQL_ROOT_PASSWORD=test1234 -e MYSQL_DATABASE=webshop -p 3306:3306 mysql:8.0
        docker run -d --name backend -p 8080:8080 lenartl/webshop-backend:sprint-1
        

    - name: Check running containers
      run: |
        docker ps --format "{{.Names}}"

    - name: Run API Tests
      run: |
       curl http://backend:8080/api/categories

    - name: Test Backend Service
      run: |
        docker exec backend curl -I http://localhost:8080/api/categories
        
    - name: Test MySQL Service
      run: |
        docker exec database -uroot -ptest1234 -e "SHOW DATABASES;"

    # - name: Run tests inside container
    #   run: |
    #     docker exec backend curl -I http://backend:8080/api/categories

    # - name: Install Newman
    #   run: npm install -g newman

    # - name: Check Localhost Service
    #   run: |
    #     curl -I http://localhost:8080/api/categories

    # - name: Run Postman Tests
    #   run: |
    #     newman run ./Postman/postman_collection.json \
    #     --environment ./Postman/postman_environment.json \
    #     --reporters cli,junit \
    #     --reporter-junit-export postman-results.xml

    - name: Test with pytest
      env:
        FRONTEND_URL: http://localhost:4200
        BACKEND_URL: http://localhost:8080
        host: localhost
        port: 3306
        user: root
        password: test1234
        database: webshop
      run: |
        pytest --alluredir=allure-results

    - name: Allure Report action from marketplace
      if: always()
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
